<?php

declare(strict_types = 1);

/**
 * Class PalindromPermutationChecker
 */
class PalindromPermutationChecker
{
    /**
     * @param string $str
     *
     * To be a permutation of a palindromme, a string can have no more
     * than one character that is odd.
     *
     * @return bool
     */
    public static function isPalindromePermutation(string $str): bool
    {
        $letters = [];

        for ($i = 0, $length = mb_strlen($str); $i < $length; $i++) {
            $char = mb_strtolower($str[$i]);

            if ($char === ' ') {
                continue;
            }

            $letters[$char] = array_key_exists($char, $letters) ? $letters[$char] + 1 : 1;
        }

        $oddCount = 0;
        foreach ($letters as $char => $count) {
            if ($count % 2 !== 0 && ++$oddCount > 1) {
                return false;
            }
        }

        return true;
    }
}

PalindromPermutationChecker::isPalindromePermutation('Tact coa'); // true -> t: 2, a: 2, c: 2, o: 1
PalindromPermutationChecker::isPalindromePermutation('coca cola'); // false -> c: 3, l: 1